application: mimondays
version: 1-5
runtime: python27
api_version: 1
threadsafe: True
libraries:
- name: jinja2
  version: latest

handlers:
- url: /static/images
  static_dir: static/images

- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

- url: /apple-touch-icon\.png
  static_files: static/images/apple-touch-icon.png
  upload: static/images/apple-touch-icon.png

- url: /test.*
  login: admin
  script: gaeunit.application

- url: /.*
  script: mondays3_5.app

error_handlers:
  - file: default_error.html

  - error_code: over_quota
    file: over_quota.html

builtins:
- remote_api: on
- appstats: on
