application: mimondays
version: 1-2-alpha2
runtime: python
api_version: 1

handlers:
- url: /static/images
  static_dir: static/images

- url: /static
  static_dir: static

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /.*
  script: mondays3_2.py

error_handlers:
- file: default_error.html

- error_code: over_quota
  file: over_quota.html

builtins:
- remote_api: on
